
# version format
version: 0.0.{build}

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: 
  - Visual Studio 2015
  - Ubuntu

build: off

stack: node 8

# Install Chrome.
install:
  - sh : sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub > google.key
  - sh : sudo apt-key add google.key
  - sh : sudo echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> google-chrome.list
  - sh : sudo cp google-chrome.list /etc/apt/sources.list.d
  - sh : sudo apt-get -y update
  - sh : sudo apt-get -y install google-chrome-stable

# to run your custom scripts instead of automatic MSBuild
build_script:
  - npm install
  - npm run package
  - npm run bundle
#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
  - cmd: npm test -- --browsers "Firefox,Chrome,IE"
  - sh: npm test -- --browsers "SmallHeadlessChrome"

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
        - path: './index.html'
          name: index.html
        - path: './play.html'
          name: 'play.html'
        - path: './lib/bundle.js'
          name: 'bundle.js'
        - path: './lib/bundle.js.map'
          name: 'bundle.js.map'
        - path: './img/MediaGoom.png'
          name: MediaGoom.png
        - path: './play.json'
          name: play.json


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:
  - provider: AzureBlob
    storage_account_name: defgroupdisks
    storage_access_key:
        secure: 7X0QuwNaLFt6pZbICyXLo4GLXRNkr81jQiyeyHty8JVewLab06xgRFb0O/lsefRnEEUyahuW4nbQ4eM0qciypNzxfsnyqUfpvbueZysU6DrFuejXQX8CCesOtlTjfKHE
    container: builds
    folder: PLAYER\$(APPVEYOR_BUILD_WORKER_IMAGE)
    artifact: index.html,play.html,bundle.js,bundle.js.map,MediaGoom.png,play.json
    unzip: false
    set_content_type: true

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Email
  - provider: Email
    to:
      - aseduto@hotmail.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    #on_build_status_changed: true

 


